version: '3'
services:
  app:
    build: .
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/tmp/.docker.xauth
      - memory:/app/resources

volumes:
  memory: